import type { PublicGroup, PublicHack } from "./types";

export const fallbackGroups: PublicGroup[] = [
  {
    id: 1,
    title: "Organic Vegetables",
    slug: "organic-vegetables",
    description:
      "Practical ideas for growing healthy vegetables without synthetic fertilizers or pesticides.",
    imageUrl: "/images/groups/organic-vegetables.jpg",
    membersCount: 4,
    hacksCount: 2,
  },
  {
    id: 2,
    title: "Balcony Gardening",
    slug: "balcony-gardening",
    description:
      "Small-space growing for balconies, windowsills, patios, and compact containers.",
    imageUrl: "/images/groups/balcony-gardening.jpg",
    membersCount: 4,
    hacksCount: 1,
  },
  {
    id: 3,
    title: "Composting Masters",
    slug: "composting-masters",
    description:
      "Compost recipes, leaf mold, worm-friendly systems, and soil food web habits.",
    imageUrl: "/images/groups/composting-masters.jpg",
    membersCount: 4,
    hacksCount: 1,
  },
  {
    id: 4,
    title: "Natural Pest Control",
    slug: "natural-pest-control",
    description:
      "Gentle prevention methods that protect crops while keeping the garden alive.",
    imageUrl: "/images/groups/natural-pest-control.jpg",
    membersCount: 4,
    hacksCount: 2,
  },
];

export const fallbackHacks: PublicHack[] = [
  {
    id: 1,
    title: "Small Garden Compost Pail That Does Not Smell",
    slug: "small-garden-compost-pail-that-does-not-smell",
    excerpt:
      "A layered kitchen-scrap pail routine that stays balanced until it is ready for the outdoor heap.",
    content:
      "Line a lidded pail with dry shredded cardboard, add chopped vegetable scraps in thin layers, and cover each fresh layer with a handful of dry leaves or finished compost. Empty it twice a week into the main pile and rinse with diluted vinegar when needed. The dry carbon layer keeps fruit flies down and gives the pile a better start.",
    imageUrl: "/images/hacks/small-garden-compost-pail-that-does-not-smell.jpg",
    category: "Composting",
    group: "Composting Masters",
    groupId: 3,
    groupSlug: "composting-masters",
    author: "Georgi Petrov",
    authorId: 1,
    difficulty: "easy",
    isOrganic: true,
    isChemicalFree: true,
    sweetTomatoesCount: 5,
    bitterCucumbersCount: 1,
    ratingScore: 4,
    commentsCount: 3,
    comments: [
      {
        id: 1,
        authorId: null,
        authorName: "Sofia Raykova",
        authorPhotoUrl: null,
        text: "This would fit nicely in a small garden because it does not need special equipment.",
        createdAt: new Date("2026-05-18T09:00:00.000Z"),
        updatedAt: new Date("2026-05-18T09:00:00.000Z"),
      },
      {
        id: 2,
        authorId: null,
        authorName: "Vasil Todorov",
        authorPhotoUrl: null,
        text: "I like that this keeps the soil covered and feeds it slowly.",
        createdAt: new Date("2026-05-19T11:30:00.000Z"),
        updatedAt: new Date("2026-05-19T11:30:00.000Z"),
      },
    ],
    isSaved: false,
    userVote: null,
    viewerGroupRole: null,
  },
  {
    id: 2,
    title: "Deep-Pot Balcony Tomatoes With Steady Moisture",
    slug: "deep-pot-balcony-tomatoes-with-steady-moisture",
    excerpt:
      "A container setup for tomatoes that reduces drying stress on hot balconies.",
    content:
      "Use a deep container with drainage, bury the tomato stem lower than usual, and add a compost-rich mix under a straw mulch cap. Water slowly in the morning until the lower soil is damp, then check again in the evening during heat waves.",
    imageUrl: "/images/hacks/deep-pot-balcony-tomatoes-with-steady-moisture.jpg",
    category: "Balcony Gardening",
    group: "Balcony Gardening",
    groupId: 2,
    groupSlug: "balcony-gardening",
    author: "Mila Stoyanova",
    authorId: 2,
    difficulty: "medium",
    isOrganic: true,
    isChemicalFree: true,
    sweetTomatoesCount: 5,
    bitterCucumbersCount: 0,
    ratingScore: 5,
    commentsCount: 3,
    comments: [
      {
        id: 3,
        authorId: null,
        authorName: "Elena Markova",
        authorPhotoUrl: null,
        text: "The steady moisture tip is useful for hot balconies.",
        createdAt: new Date("2026-05-20T14:15:00.000Z"),
        updatedAt: new Date("2026-05-20T14:15:00.000Z"),
      },
    ],
    isSaved: false,
    userVote: null,
    viewerGroupRole: null,
  },
  {
    id: 3,
    title: "Leaf Mold Soil Sponge for Tired Beds",
    slug: "leaf-mold-soil-sponge-for-tired-beds",
    excerpt:
      "Use aged leaves to improve water holding and soil texture without synthetic additives.",
    content:
      "Collect fallen leaves, moisten them, and pack them into a breathable sack or simple wire ring. After several months, crumble the dark material over beds before mulching. Leaf mold feeds soil life gently, improves moisture retention, and is especially useful in beds that crust after watering.",
    imageUrl: "/images/hacks/leaf-mold-soil-sponge-for-tired-beds.jpg",
    category: "Soil Regeneration",
    group: "Soil Regeneration",
    groupId: 0,
    groupSlug: "soil-regeneration",
    author: "Vasil Todorov",
    authorId: 3,
    difficulty: "medium",
    isOrganic: true,
    isChemicalFree: true,
    sweetTomatoesCount: 5,
    bitterCucumbersCount: 1,
    ratingScore: 4,
    commentsCount: 3,
    comments: [],
    isSaved: false,
    userVote: null,
    viewerGroupRole: null,
  },
];
